### PR TITLE
added Dutch locale

### PR DESCRIPTION
**Pull request by brambex**
Hi,

This is a PR with:
- a Dutch locale (I am willing to maintain it in the future)
- bugfix for language selection in Chrome
old
selection options appear as white text on a white background
new
updated the default (outlined) background to `bg-main-dark` because I felt that this was the initial design

### CODE REVIEW

**Comment by bstnfrmry** [comment]
Hey @brambex, thank you so much for the PR! I'll review it tomorrow 👍

**Comment by bstnfrmry** [comment]
Everything looked good! It's merged 🎉 

It just updated the flag/name so it's more consistent with ours.

image.

Maintenance will might be a bit annoying. We very often add new keys and won't be able to translate them. So they will fallback in english in the meantime. I guess it's not too problematic.

**Comment by bstnfrmry** [comment]
By the way, we also released a "Game summary" page this week-end but it hasn't been translated yet (https://hanabi.cards/summary?gameId=udVsP7ebn)

**Comment by brambex** [comment]
@bstnfrmry Yes, I've seen it. Somebody picked it up already or can I work on it in a new branch?

**Comment by bstnfrmry** [comment]
@brambex We haven't started anything yet so you can create a new branch 👍

**Pull request merged**
